import * as THREE from './three.module.js';
const $=id=>document.getElementById(id);
const names=['Acceso noreste','Sendero noreste','Plaza de juegos','Sendero sureste','Zona de juegos','Fuente · lado este','Acceso sureste','Pérgola sur','Fuente · lado sur','Acceso suroeste','Sendero suroeste','Plaza de descanso','Zona de descanso','Sendero noroeste','Acceso noroeste','Pérgola norte','Fuente · lado norte','Fuente · lado oeste'];
const xy=[[970,95],[818,190],[914,375],[831,538],[786,374],[606,374],[973,671],[550,669],[546,456],[110,670],[250,558],[131,375],[288,375],[263,194],[129,81],[541,73],[540,290],[455,375]];
const edges=[[1,2],[2,6],[3,5],[4,6],[5,6],[7,4],[8,9],[9,6],[10,11],[11,18],[12,13],[13,18],[14,18],[15,14],[16,17],[17,6],[18,17],[18,9]];
const neighbors=id=>edges.filter(e=>e.includes(id)).map(e=>e[0]===id?e[1]:e[0]);
const bearing=(a,b)=>Math.atan2(b[0]-a[0],a[1]-b[1]);
const fronts=xy.map((p,i)=>bearing(p,i===2?xy[4]:i===11?xy[12]:[538,375]));
let renderer,scene,camera,activeSphere=null,current=1,mode=1,yaw=fronts[0],pitch=0,busy=false,requestId=0,transition=null,hotspots=[],vrObjects=[],first=true,noticeTimer,drag=null;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,cache=new Map(),pending=new Map(),loader=new THREE.TextureLoader();
const metrics={loadedBytes:0,loads:0,lastLoadMs:0};
function notice(s){$('notice').textContent=s;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,6000)}
function loading(v,s='Abriendo la siguiente vista…'){$('loading').hidden=!v;$('loading-text').textContent=s}
function fail(err){$('error').hidden=false;$('error-text').textContent=err.message||String(err);loading(false)}
const geometry=new THREE.SphereGeometry(40,64,40);geometry.scale(-1,1,1);
function makeSphere(texture,id){const m=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({map:texture,transparent:true,opacity:1,depthWrite:false}));m.rotation.y=-Math.PI/2-fronts[id-1];m.renderOrder=0;scene.add(m);return m}
function disposeSphere(s){if(s){scene.remove(s);s.material.dispose()}}
function prune(){const inUse=new Set([activeSphere?.material.map,transition?.old.material.map,transition?.next.material.map]);for(const [k,t] of cache){if(cache.size<=6)break;if(!inUse.has(t)){cache.delete(k);t.dispose()}}}
async function texture(id,light,quality){const key=`${String(id).padStart(2,'0')}-${light}-${quality}`;if(cache.has(key)){const t=cache.get(key);cache.delete(key);cache.set(key,t);return t}if(pending.has(key))return pending.get(key);const started=performance.now();const promise=loader.loadAsync(`${key}.jpg`).then(t=>{t.colorSpace=THREE.SRGBColorSpace;t.generateMipmaps=false;t.minFilter=THREE.LinearFilter;cache.set(key,t);metrics.loads++;metrics.lastLoadMs=Math.round(performance.now()-started);pending.delete(key);prune();return t}).catch(e=>{pending.delete(key);throw e});pending.set(key,promise);return promise}
function finishTransition(){if(!transition)return;transition.next.material.opacity=1;disposeSphere(transition.old);activeSphere=transition.next;transition.resolve();transition=null;prune()}
async function fadeTo(t,id){if(transition)finishTransition();const next=makeSphere(t,id);if(!activeSphere){activeSphere=next;return}next.renderOrder=1;next.material.opacity=0;await new Promise(resolve=>{transition={old:activeSphere,next,start:performance.now(),duration:reduced?1:520,resolve}});next.renderOrder=0}
async function go(id,light=mode,center=false){if(busy)return;const token=++requestId;busy=true;loading(true,first?'Preparando el parque…':'Abriendo la siguiente vista…');$('hotspots').style.visibility='hidden';try{const t=await texture(id,light,'preview');if(token!==requestId)return;if(center)yaw=fronts[id-1];await fadeTo(t,id);current=id;mode=light;first=false;updateUI();buildHotspots();loading(false);const quality=renderer.capabilities.maxTextureSize>=4096?'hd':'preview';texture(id,light,quality).then(async high=>{if(token!==requestId||activeSphere.material.map===high)return;await fadeTo(high,id)}).catch(()=>notice('La vista sigue disponible; no se pudo cargar su versión de mayor detalle.'));}catch(e){loading(false);if(first)fail(new Error('Revisa la conexión local y vuelve a intentar. Tu navegador también debe permitir gráficos 3D.'));else notice('No pudimos cargar esa vista. Puedes volver a intentarlo.')}finally{busy=false;$('hotspots').style.visibility='visible'}}
function updateUI(){$('point').textContent=`${String(current).padStart(2,'0')} / 18`;$('place-name').textContent=names[current-1];$('day').setAttribute('aria-pressed',mode===1);$('night').setAttribute('aria-pressed',mode===2);document.querySelectorAll('#map button').forEach(b=>b.setAttribute('aria-current',Number(b.dataset.id)===current));$('nearby').replaceChildren(...neighbors(current).map(id=>{const b=document.createElement('button');b.textContent=`${String(id).padStart(2,'0')} · ${names[id-1]}`;b.onclick=()=>go(id);return b}));document.title=`${names[current-1]} · ${mode===1?'Día':'Noche'} | RVISIOON Parque 360`}
function buildMap(){$('map').innerHTML=`<svg viewBox="-36 -36 1124 763" aria-hidden="true"><rect x="60" y="52" width="952" height="620" rx="18" fill="#66735c"/><path d="M100 95H970V660H100Z M100 95L970 660 M970 95L100 660 M540 75V670 M135 375H920" fill="none" stroke="#c7bdac" stroke-width="35" stroke-linejoin="round"/><circle cx="540" cy="375" r="90" fill="#c7bdac"/><circle cx="540" cy="375" r="39" fill="#647d8a" stroke="#e5e0d5" stroke-width="7"/><circle cx="200" cy="375" r="69" fill="#92937a"/><circle cx="854" cy="375" r="69" fill="#a6a079"/><rect x="390" y="80" width="130" height="60" rx="6" fill="#584b41"/><rect x="580" y="585" width="130" height="60" rx="6" fill="#584b41"/><g stroke="#b196cf" stroke-width="3" opacity=".6">${edges.map(([a,b])=>`<path d="M${xy[a-1].join(' ')} L${xy[b-1].join(' ')}"/>`).join('')}</g></svg>`;xy.forEach((p,i)=>{const b=document.createElement('button');b.textContent=i+1;b.dataset.id=i+1;b.style.left=`${(p[0]+36)/1124*100}%`;b.style.top=`${(p[1]+36)/763*100}%`;b.setAttribute('aria-label',`Punto ${i+1}: ${names[i]}`);b.onclick=()=>{go(i+1,mode,true);$('map-panel').hidden=true;$('map-toggle').setAttribute('aria-expanded','false')};$('map').append(b)})}
function buildHotspots(){hotspots.forEach(h=>{scene.remove(h.mesh);h.mesh.geometry.dispose();h.mesh.material.dispose()});hotspots=[];$('hotspots').replaceChildren();neighbors(current).forEach(id=>{const a=bearing(xy[current-1],xy[id-1]);const d=Math.min(7,Math.max(3.2,Math.hypot(xy[id-1][0]-xy[current-1][0],xy[id-1][1]-xy[current-1][1])/40));const pos=new THREE.Vector3(Math.sin(a)*d,-1.55,-Math.cos(a)*d);const mesh=new THREE.Mesh(new THREE.TorusGeometry(.24,.045,8,32),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.86,depthTest:false}));mesh.rotation.x=-Math.PI/2;mesh.position.copy(pos);mesh.renderOrder=3;mesh.userData.target=id;mesh.visible=renderer.xr.isPresenting;scene.add(mesh);const button=document.createElement('button');button.className='hotspot';button.textContent=String(id).padStart(2,'0');button.dataset.label=names[id-1];button.setAttribute('aria-label',`Ir al punto ${id}: ${names[id-1]}`);button.onclick=()=>go(id);$('hotspots').append(button);hotspots.push({id,pos,mesh,button})});vrObjects=hotspots.map(h=>h.mesh);if(vrToggle)vrObjects.push(vrToggle)}
let vrToggle=null;const raycaster=new THREE.Raycaster(),rotation=new THREE.Matrix4();
function setupVR(){if(navigator.xr)navigator.xr.isSessionSupported('immersive-vr').then(ok=>{if(ok)document.body.classList.add('vr-available')}).catch(()=>{});const viewRig=new THREE.Group();scene.add(viewRig);viewRig.add(camera);renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local');renderer.xr.addEventListener('sessionstart',()=>{document.body.classList.add('in-vr');viewRig.rotation.y=-yaw;camera.rotation.set(0,0,0);vrToggle.position.set(Math.sin(yaw)*2.5,-.55,-Math.cos(yaw)*2.5);vrToggle.rotation.y=-yaw;hotspots.forEach(h=>h.mesh.visible=true);vrToggle.visible=true});renderer.xr.addEventListener('sessionend',()=>{document.body.classList.remove('in-vr');viewRig.rotation.y=0;camera.position.set(0,0,0);hotspots.forEach(h=>h.mesh.visible=false);vrToggle.visible=false;$('vr').textContent='Modo VR'});const cv=document.createElement('canvas');cv.width=512;cv.height=128;const c=cv.getContext('2d');c.fillStyle='#332442';c.fillRect(0,0,512,128);c.fillStyle='#fff';c.font='36px Arial';c.textAlign='center';c.fillText('Día / Noche',256,78);const t=new THREE.CanvasTexture(cv);t.colorSpace=THREE.SRGBColorSpace;vrToggle=new THREE.Mesh(new THREE.PlaneGeometry(1.2,.3),new THREE.MeshBasicMaterial({map:t,side:THREE.DoubleSide,depthTest:false}));vrToggle.position.set(0,-.55,-2.5);vrToggle.visible=false;vrToggle.renderOrder=4;scene.add(vrToggle);for(let i=0;i<2;i++){const controller=renderer.xr.getController(i);controller.addEventListener('select',()=>{rotation.extractRotation(controller.matrixWorld);raycaster.ray.origin.setFromMatrixPosition(controller.matrixWorld);raycaster.ray.direction.set(0,0,-1).applyMatrix4(rotation);const hit=raycaster.intersectObjects(vrObjects)[0];if(hit){if(hit.object===vrToggle)go(current,mode===1?2:1);else go(hit.object.userData.target)}});const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-8)]),new THREE.LineBasicMaterial({color:0xcba6f1,transparent:true,opacity:.5}));controller.add(line);viewRig.add(controller)}$('vr').onclick=async()=>{try{if(renderer.xr.getSession()){await renderer.xr.getSession().end();return}if(!navigator.xr||!await navigator.xr.isSessionSupported('immersive-vr')){notice('Abre este recorrido desde el navegador de tus lentes compatibles para entrar en VR.');return}const session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor']});await renderer.xr.setSession(session);$('vr').textContent='Salir de VR'}catch(e){notice('No se pudo iniciar VR. Comprueba que el visor esté conectado y que tenga permiso.')}}}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight)}
function frame(now){if(transition){const f=Math.min(1,(now-transition.start)/transition.duration);transition.next.material.opacity=f*f*(3-2*f);if(f===1)finishTransition()}if(!renderer.xr.isPresenting){camera.rotation.set(pitch,-yaw,0,'YXZ');camera.updateMatrixWorld();const forward=new THREE.Vector3();camera.getWorldDirection(forward);hotspots.forEach(h=>{const projected=h.pos.clone().project(camera);const visible=h.pos.dot(forward)>0&&projected.z<1&&projected.x>-1&&projected.x<1&&projected.y>-.7&&projected.y<.65;h.button.hidden=!visible;h.button.style.left=`${(projected.x+1)*innerWidth/2}px`;h.button.style.top=`${(1-projected.y)*innerHeight/2}px`})}else{const xrCamera=renderer.xr.getCamera();const p=new THREE.Vector3().setFromMatrixPosition(xrCamera.matrixWorld);activeSphere?.position.copy(p);if(transition){transition.old.position.copy(p);transition.next.position.copy(p)}}renderer.render(scene,camera);if(!$('debug').hidden){const fetched=performance.getEntriesByType('resource').filter(e=>e.name.includes('/panoramas/'));$('debug').textContent=`Punto ${current} / ${mode===1?'día':'noche'}\n${fetched.length} imágenes solicitadas · ${(fetched.reduce((s,e)=>s+e.transferSize,0)/1048576).toFixed(2)} MB\nÚltima carga: ${metrics.lastLoadMs} ms\nTexturas en memoria: ${renderer.info.memory.textures}`}}
try{scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,80);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0x16121e);$('viewer').append(renderer.domElement);resize();setupVR();buildMap();updateUI();renderer.setAnimationLoop(frame);go(1);const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,yaw,pitch};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw=drag.yaw-(e.clientX-drag.x)*.0035;pitch=THREE.MathUtils.clamp(drag.pitch+(e.clientY-drag.y)*.0035,-1.1,1.1)});const release=()=>drag=null;canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('wheel',e=>{e.preventDefault();camera.fov=THREE.MathUtils.clamp(camera.fov+e.deltaY*.025,45,90);camera.updateProjectionMatrix()},{passive:false});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();notice('El visor se pausó. Recarga la página para recuperar la imagen.')});addEventListener('resize',resize);addEventListener('keydown',e=>{if(e.target.tagName==='BUTTON')return;if(e.key==='ArrowLeft')yaw-=.1;if(e.key==='ArrowRight')yaw+=.1;if(e.key==='ArrowUp')pitch=Math.min(1.1,pitch+.08);if(e.key==='ArrowDown')pitch=Math.max(-1.1,pitch-.08);if(e.key==='Escape'){$('map-panel').hidden=true;$('map-toggle').setAttribute('aria-expanded','false')}});$('day').onclick=()=>go(current,1);$('night').onclick=()=>go(current,2);$('reset').onclick=()=>{yaw=fronts[current-1];pitch=0;camera.fov=72;camera.updateProjectionMatrix()};$('map-toggle').onclick=()=>{const open=$('map-panel').hidden;$('map-panel').hidden=!open;$('map-toggle').setAttribute('aria-expanded',open)};$('map-close').onclick=()=>{$('map-panel').hidden=true;$('map-toggle').setAttribute('aria-expanded','false')};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('tour').requestFullscreen()}catch(e){notice('Puedes ampliar el recorrido usando la pantalla completa de tu navegador.')}};$('debug').hidden=!new URLSearchParams(location.search).has('debug')}catch(e){fail(e)}
